/**
 * 表情 SVG 文件静态映射
 * 由于 Metro bundler 不支持动态 require，需要静态映射所有文件
 */
export const EMOJI_ASSETS: Record<string, any> = {
  'anxious_face_with_sweat_color.svg': require('@/assets/emojis/anxious_face_with_sweat_color.svg'),
  'astonished_face_color.svg': require('@/assets/emojis/astonished_face_color.svg'),
  'beaming_face_with_smiling_eyes_color.svg': require('@/assets/emojis/beaming_face_with_smiling_eyes_color.svg'),
  'cold_face_color.svg': require('@/assets/emojis/cold_face_color.svg'),
  'confounded_face_color.svg': require('@/assets/emojis/confounded_face_color.svg'),
  'disappointed_face_color.svg': require('@/assets/emojis/disappointed_face_color.svg'),
  'downcast_face_with_sweat_color.svg': require('@/assets/emojis/downcast_face_with_sweat_color.svg'),
  'drooling_face_color.svg': require('@/assets/emojis/drooling_face_color.svg'),
  'expressionless_face_color.svg': require('@/assets/emojis/expressionless_face_color.svg'),
  'face_blowing_a_kiss_color.svg': require('@/assets/emojis/face_blowing_a_kiss_color.svg'),
  'face_exhaling_color.svg': require('@/assets/emojis/face_exhaling_color.svg'),
  'face_holding_back_tears_color.svg': require('@/assets/emojis/face_holding_back_tears_color.svg'),
  'face_savoring_food_color.svg': require('@/assets/emojis/face_savoring_food_color.svg'),
  'face_screaming_in_fear_color.svg': require('@/assets/emojis/face_screaming_in_fear_color.svg'),
  'face_vomiting_color.svg': require('@/assets/emojis/face_vomiting_color.svg'),
  'face_with_hand_over_mouth_color.svg': require('@/assets/emojis/face_with_hand_over_mouth_color.svg'),
  'face_with_medical_mask_color.svg': require('@/assets/emojis/face_with_medical_mask_color.svg'),
  'face_with_peeking_eye_color.svg': require('@/assets/emojis/face_with_peeking_eye_color.svg'),
  'face_with_raised_eyebrow_color.svg': require('@/assets/emojis/face_with_raised_eyebrow_color.svg'),
  'face_with_rolling_eyes_color.svg': require('@/assets/emojis/face_with_rolling_eyes_color.svg'),
  'face_with_spiral_eyes_color.svg': require('@/assets/emojis/face_with_spiral_eyes_color.svg'),
  'face_with_steam_from_nose_color.svg': require('@/assets/emojis/face_with_steam_from_nose_color.svg'),
  'face_with_symbols_on_mouth_color.svg': require('@/assets/emojis/face_with_symbols_on_mouth_color.svg'),
  'face_with_tears_of_joy_color.svg': require('@/assets/emojis/face_with_tears_of_joy_color.svg'),
  'face_with_thermometer_color.svg': require('@/assets/emojis/face_with_thermometer_color.svg'),
  'face_with_tongue_color.svg': require('@/assets/emojis/face_with_tongue_color.svg'),
  'fearful_face_color.svg': require('@/assets/emojis/fearful_face_color.svg'),
  'grimacing_face_color.svg': require('@/assets/emojis/grimacing_face_color.svg'),
  'grinning_face_color.svg': require('@/assets/emojis/grinning_face_color.svg'),
  'grinning_face_with_smiling_eyes_color.svg': require('@/assets/emojis/grinning_face_with_smiling_eyes_color.svg'),
  'grinning_face_with_sweat_color.svg': require('@/assets/emojis/grinning_face_with_sweat_color.svg'),
  'grinning_squinting_face_color.svg': require('@/assets/emojis/grinning_squinting_face_color.svg'),
  'hot_face_color.svg': require('@/assets/emojis/hot_face_color.svg'),
  'hugging_face_color.svg': require('@/assets/emojis/hugging_face_color.svg'),
  'kissing_face_color.svg': require('@/assets/emojis/kissing_face_color.svg'),
  'knocked-out_face_color.svg': require('@/assets/emojis/knocked-out_face_color.svg'),
  'loudly_crying_face_color.svg': require('@/assets/emojis/loudly_crying_face_color.svg'),
  'melting_face_color.svg': require('@/assets/emojis/melting_face_color.svg'),
  'money-mouth_face_color.svg': require('@/assets/emojis/money-mouth_face_color.svg'),
  'neutral_face_color.svg': require('@/assets/emojis/neutral_face_color.svg'),
  'partying_face_color.svg': require('@/assets/emojis/partying_face_color.svg'),
  'persevering_face_color.svg': require('@/assets/emojis/persevering_face_color.svg'),
  'pleading_face_color.svg': require('@/assets/emojis/pleading_face_color.svg'),
  'pouting_face_color.svg': require('@/assets/emojis/pouting_face_color.svg'),
  'rolling_on_the_floor_laughing_color.svg': require('@/assets/emojis/rolling_on_the_floor_laughing_color.svg'),
  'saluting_face_color.svg': require('@/assets/emojis/saluting_face_color.svg'),
  'shushing_face_color.svg': require('@/assets/emojis/shushing_face_color.svg'),
  'slightly_frowning_face_color.svg': require('@/assets/emojis/slightly_frowning_face_color.svg'),
  'slightly_smiling_face_color.svg': require('@/assets/emojis/slightly_smiling_face_color.svg'),
  'smiling_face_color.svg': require('@/assets/emojis/smiling_face_color.svg'),
  'smiling_face_with_halo_color.svg': require('@/assets/emojis/smiling_face_with_halo_color.svg'),
  'smiling_face_with_heart-eyes_color.svg': require('@/assets/emojis/smiling_face_with_heart-eyes_color.svg'),
  'smiling_face_with_hearts_color.svg': require('@/assets/emojis/smiling_face_with_hearts_color.svg'),
  'smiling_face_with_smiling_eyes_color.svg': require('@/assets/emojis/smiling_face_with_smiling_eyes_color.svg'),
  'smiling_face_with_sunglasses_color.svg': require('@/assets/emojis/smiling_face_with_sunglasses_color.svg'),
  'smiling_face_with_tear_color.svg': require('@/assets/emojis/smiling_face_with_tear_color.svg'),
  'smirking_face_color.svg': require('@/assets/emojis/smirking_face_color.svg'),
  'sneezing_face_color.svg': require('@/assets/emojis/sneezing_face_color.svg'),
  'squinting_face_with_tongue_color.svg': require('@/assets/emojis/squinting_face_with_tongue_color.svg'),
  'star-struck_color.svg': require('@/assets/emojis/star-struck_color.svg'),
  'thinking_face_color.svg': require('@/assets/emojis/thinking_face_color.svg'),
  'tired_face_color.svg': require('@/assets/emojis/tired_face_color.svg'),
  'unamused_face_color.svg': require('@/assets/emojis/unamused_face_color.svg'),
  'upside-down_face_color.svg': require('@/assets/emojis/upside-down_face_color.svg'),
  'weary_face_color.svg': require('@/assets/emojis/weary_face_color.svg'),
  'winking_face_color.svg': require('@/assets/emojis/winking_face_color.svg'),
  'winking_face_with_tongue_color.svg': require('@/assets/emojis/winking_face_with_tongue_color.svg'),
  'yawning_face_color.svg': require('@/assets/emojis/yawning_face_color.svg'),
  'zany_face_color.svg': require('@/assets/emojis/zany_face_color.svg'),
  'zipper-mouth_face_color.svg': require('@/assets/emojis/zipper-mouth_face_color.svg'),
};

